sonar.projectKey=snirnach_LatentSpace-Explorer
sonar.organization=snirnach

# This is the name displayed in the SonarCloud UI
sonar.projectName=LatentSpace-Explorer

# Pointing exactly to your Java source files
sonar.sources=src

# Encoding of the source code
sonar.sourceEncoding=UTF-8
